language: php

matrix:
  include:
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3
  - php: 7.4
  - php: nightly
  fast_finish: true
  allow_failures:
  - php: nightly

before_script:
  - phpenv config-rm xdebug.ini
  
script: cd Tests && phpunit --configuration phpunit.xml
